#kubectl create configmap test-config --from-literal=test-key=5
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
    resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    env:
      - name: TEST_VALUE
        valueFrom:
          configMapKeyRef:
            name: test-config
            key: test-key
   
  restartPolicy: Never
# kubectl apply -f pod-configmap-envFrom.yaml  
# kubectl logs test-pod  
# kubectl delete configmaps test-config