# kubectl create -f configmap-multikeys.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - configMapRef:
        name: special-config
  restartPolicy: Never
# kubectl apply -f pod-configmap-envFrom.yaml
# kubectl logs test-pod  
# kubectl delete -f pod-configmap-envFrom.yaml
# kubectl delete -f configmap-multikeys.yaml